### ISSUE TITLE
Icons not rendered in stackoverflow template

### ISSUE THREAD

**Issue by francois07** [lucasnevespereira/resumme-builder#10]
When using the stackoverflow template, FontAwesome icons are not rendered in the output .pdf file. They are rendered properly in the .html output and when printing this .html file to pdf, they are properly rendered. This bug does not occur when rendering with the oldman template which uses FontAwesome icons too

# Steps to reproduce

1. In the `resume.json` file, specify any field that the stackoverflow template adds icons to such as `basics.email`
2. Run resumme-builder in local mode

**Comment by lucasnevespereira** [comment]
Hello @francois07 
I've just tried to generate the `stackoverflow` template with the `example.resume.json` file and icons seem to be working.

<img width="600" alt="Screenshot 2024-07-09 at 22 02 32" src="https://github.com/lucasnevespereira/resumme-builder/assets/44783073/26342d01-f99e-491d-bb82-8afe8edd0b09">

I am running this on macOS, by the way. Do you still have the issue ?

**Comment by francois07** [comment]
Hello @lucasnevespereira. Yes, I still have this issue. I tested it on Windows and Linux. This is really puzzling to me because even when importing FontAwesome icons exactly the same way as the oldman theme, this still happens.

![image](https://github.com/lucasnevespereira/resumme-builder/assets/6379436/19c6d6a4-7451-4354-a81b-635b9ef553b5)

**Comment by lucasnevespereira** [comment]
@francois07 the main difference I see between template `oldman` and `stackoverflow` regarding the icons is the way we import fontawesome

`oldman`
```
...
<script src="https://kit.fontawesome.com/990c3c315f.js" crossorigin="anonymous"></script>
```

`stackoverflow`
```
...
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
```

Have you tried to import it the way `oldman` does ?

**Comment by lucasnevespereira** [comment]
Hello @francois07, alright then! If everything seems to work on your end, I'll close this issue
