### ISSUE TITLE
Reopen #10

### ISSUE THREAD

**Issue by francois07** [lucasnevespereira/resumme-builder#17]
As I am unable to re-open issues, I'm creating a new one. See my previous comment in #10 below.

I'm opening this issue once again. I've noticed that this problem still happens but quite randomly. Amazingly, my previous guess was spot on an after researching it some more, I came across the following related issue chromedp/chromedp#1390

It seems like we need to listen to the `networkIdle` event to make sure icons have been loaded first (see https://github.com/chromedp/chromedp/issues/1390#issuecomment-1783999997) in `internal/pkg/pdf/generator.go` instead of checking if the body is visible.

_Originally posted by @francois07 in https://github.com/lucasnevespereira/resumme-builder/issues/10#issuecomment-2353184213_

**Comment by lucasnevespereira** [comment]
Hello @francois07,

Thank you for bringing this to my attention again and for the detailed research.
I will take on this issue and implement a solution to listen for the `networkIdle` event to ensure that all icons and resources are fully loaded before generating the PDF.

I'll keep you updated on the progress.

Regards, Lucas

**Comment by lucasnevespereira** [comment]
@francois07 Let me know if this solved the problem on your end. If not, I'll open another issue

**Comment by francois07** [comment]
Hye @lucasnevespereira, thank you for the quick answer ! It looks good to me
